resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 1000
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true