spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show_sql: false
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6431/smart-home
    username: dbuser
    password: 12345

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      hub:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
        group-id: hubEvent.group.id
        client-id: HubEventConsumer
        auto-offset-reset: earliest
        enable-auto-commit: false
      snapshots:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer
        group-id: snapshot.group.id
        client-id: SnapshotsConsumer
        auto-offset-reset: earliest
        enable-auto-commit: false

server:
  port: 8083

analyzer:
  topic:
    snapshots-topic: telemetry.snapshots.v1
    hub-event-topic: telemetry.hubs.v1

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext