# Hibernate
spring:
  jpa:
    hibernate:
      ddl-auto: update

  # Postgres
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6433/store-db
    username: dbuser
    password: '12345'

server:
  port: 0